/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import hieu.compiler.CompileResult;
import hieu.compiler.Compiler;
import hieu.utils.Utils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.io.IOException;

import static org.junit.Assert.assertEquals;

public class CompilerTest {
	private File testDir;

	@Before
	public void init() {
		testDir = new File("testDir");
		if (!testDir.exists()) {
			testDir.mkdir();
		}
	}

	@After
	public void delete() {
		Utils.deleteDirectory(testDir);
	}

    @Test
	public void testJavaCompiler() throws IOException {
		CompileResult result = null;
		String codeText = "public class Main{ public static void main(String[] argv) {}}";
		result = Compiler.compileJavaProgram(testDir, codeText);
		assertEquals(result.isSuccess(), true);

		codeText += "}";
		result = Compiler.compileJavaProgram(testDir, codeText);
		assertEquals(result.isSuccess(), false);

	}

	@Test
	public void testClangCompiler() throws IOException {
		CompileResult result = null;
		String codeText = "int main(){for(int i=0; i<100; i++){}return 0;}";

		result = Compiler.compileClangProgram(testDir, codeText);
        System.out.print(result.getErrorMsg());
		assertEquals(result.isSuccess(), true);

		codeText += "}";
		result = Compiler.compileClangProgram(testDir, codeText);
		assertEquals(result.isSuccess(), false);
	}

    @Test
    public void testCplusplusCompiler() throws IOException {
        CompileResult result = null;
        String codeText = "#include<iostream>\nint main(){for(int i=0; i<100; i++){}return 0;}";

        result = Compiler.compileCPlusPlusProgram(testDir, codeText);
        System.out.print(result.getErrorMsg());
        assertEquals(result.isSuccess(), true);

        codeText += "}";
        result = Compiler.compileCPlusPlusProgram(testDir, codeText);
        assertEquals(result.isSuccess(), false);
    }
}
